# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.195.0/containers/javascript-node/.devcontainer/base.Dockerfile
ARG VARIANT=20-alpine
FROM mcr.microsoft.com/devcontainers/javascript-node:0-${VARIANT}